version: "3.8"
services:
    mysql:
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev_user
            - MYSQL_PASSWORD=secretpassword
            - MYSQL_DATABASE=papertrail_dev
        ports:
            - "3306:3306"
        volumes:
            - ./utils/00_paperTrailDBInit.sql:/docker-entrypoint-initdb.d/00_paperTrailDBInit.sql

    web-test:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.dev
        command: ./wait-for-it.sh mysql:3306 -t 0 -- yarn run test
        ports:
            - "8081:8081"
        depends_on: 
            - mysql
        volumes:
            - ./package.json:/code/package.json
            - ./src:/code/src
        environment:
            - NODE_ENV=testing
            - PORT=8081
            - db_database=papertrail_dev
            - db_host=mysql
            - db_password=secretpassword
            - db_user=dev_user

volumes:
    papertrail_tests:
        driver: local