version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./package.json:/code/package.json
            - ./src:/code/src
        environment:
            - NODE_ENV=heroku
            - PORT=3000