version: "3.8"
services:
    mysql:
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev_user
            - MYSQL_PASSWORD=secretpassword
            - MYSQL_DATABASE=papertrail_dev
        ports:
            - "3306:3306"
        volumes:
            - ./utils/00_paperTrailDBInit.sql:/docker-entrypoint-initdb.d/AppDatabase.sql

    web:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./package.json:/code/package.json
            - ./webpack.config.ts:/code/webpack.config.ts
            - ./src:/code/src
        environment:
            - NODE_ENV=development
            - PORT=3000
            - db_database=papertrail_dev
            - db_host=mysql
            - db_password=secretpassword
            - db_user=dev_user
