FROM node:10.12.0
EXPOSE 4004

WORKDIR /code

# ENV PYTHONUNBUFFERED=1
# RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
# RUN python3 -m ensurepip
# RUN pip3 install --no-cache --upgrade pip setuptools

COPY ./bc_src/package.json .
RUN yarn install

COPY ./bc_src .
CMD yarn start