FROM node:12.18.4
EXPOSE 8081

WORKDIR /code

COPY package.json .
COPY /utils/wait-for-it.sh .
RUN chmod +x ./wait-for-it.sh
RUN yarn install

COPY . .
CMD yarn build-ts && yarn run watch
